---
Parameters:
  WAFDescription:
			Type: String
			Description: Description for WAF purpose and general use

Resources:
	SampleWAF:
    Type: AWS::WAF::WebACL
    Properties:
			DefaultAction: ALLOW
			Name: SampleWAF
			Rules:
				- Action: ALLOW
					Priority: 1
					RuleId: BasicWAFRule

	SampleCloudfront:
		Type: AWS::Cloudfront:Distribution
		Properties:
			DistributionConfig:
				WebACLId: !Ref SampleWAF
				Origins:
					- DomainName: "sampleDomain.com"
						Id: sampleOrigin
						CustomOriginConfig:
							HTTPPort: 80
							HTTPSPort: 443
							OriginProtocolPolicy: http-only
				Enabled: true
				DefaultRootObject: index.html
				CustomErrorResponses: 
					- ErrorCode: 404
						ResponsePagePath: "/error-pages/404.html"
						ResponseCode: 200
						ErrorCachingMinTTL: 30
